# Generated by Django 5.0.7 on 2024-09-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Top Wear', 'Top Wear'), ('Bottom Wear', 'Bottom Wear')], max_length=121),
        ),
    ]
